<?php

namespace ContainerBl6OzCN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIniciControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\IniciController' shared autowired service.
     *
     * @return \App\Controller\IniciController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/IniciController.php';

        $container->services['App\\Controller\\IniciController'] = $instance = new \App\Controller\IniciController();

        $instance->setContainer(($container->privates['.service_locator.uT.fSCP'] ?? $container->load('get_ServiceLocator_UT_FSCPService'))->withContext('App\\Controller\\IniciController', $container));

        return $instance;
    }
}
