<?php

namespace Container8ebWXWi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPeixosControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PeixosController' shared autowired service.
     *
     * @return \App\Controller\PeixosController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PeixosController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/DadesPeixos.php';

        $container->services['App\\Controller\\PeixosController'] = $instance = new \App\Controller\PeixosController(($container->services['App\\Service\\DadesPeixos'] ?? ($container->services['App\\Service\\DadesPeixos'] = new \App\Service\DadesPeixos())));

        $instance->setContainer(($container->privates['.service_locator.uT.fSCP'] ?? $container->load('get_ServiceLocator_UT_FSCPService'))->withContext('App\\Controller\\PeixosController', $container));

        return $instance;
    }
}
