<?php

namespace ContainerSw1xerm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDadesPeixosService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\DadesPeixos' shared autowired service.
     *
     * @return \App\Service\DadesPeixos
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/DadesPeixos.php';

        return $container->services['App\\Service\\DadesPeixos'] = new \App\Service\DadesPeixos();
    }
}
