<?php

namespace ContainerRtezfiY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPeixTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Form\PeixType' shared autowired service.
     *
     * @return \App\Form\PeixType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/PeixType.php';

        return $container->services['App\\Form\\PeixType'] = new \App\Form\PeixType();
    }
}
