<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRtezfiY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRtezfiY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRtezfiY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRtezfiY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRtezfiY\App_KernelDevDebugContainer([
    'container.build_hash' => 'RtezfiY',
    'container.build_id' => 'bae47108',
    'container.build_time' => 1674796390,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRtezfiY');
