<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSw1xerm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSw1xerm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSw1xerm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSw1xerm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSw1xerm\App_KernelDevDebugContainer([
    'container.build_hash' => 'Sw1xerm',
    'container.build_id' => 'dcb8496d',
    'container.build_time' => 1674802144,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSw1xerm');
