<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBl6OzCN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBl6OzCN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBl6OzCN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBl6OzCN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBl6OzCN\App_KernelDevDebugContainer([
    'container.build_hash' => 'Bl6OzCN',
    'container.build_id' => '192e0c9e',
    'container.build_time' => 1674800097,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBl6OzCN');
